version: 0.2

env:
  variables:
      AWS_DEFAULT_REGION: "us-east-1"
      AWS_ACCOUNT_ID: "042469170563"
<<<<<<< HEAD
      VERSION: 0.6.1
=======
      VERSION: 0.6.2
>>>>>>> 5ebe5126fd4c519aeef90bc7717b9d9fee3870aa
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build version $VERSION started on `date`
      - docker build -t mznotifier:$VERSION .
      - docker tag mznotifier:$VERSION $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/mznotifier:$VERSION
      - docker tag mznotifier:$VERSION $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/mznotifier:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/mznotifier:$VERSION
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/mznotifier:latest
